### ISSUE TITLE
Learn IDE doesn't contain necessary files

### ISSUE THREAD

**Issue by ahotchkin** [learn-co-curriculum/layouts-grids-code-along#10]
When I open the IDE for this lab the only files there are CONTRIBUTING.md and README.md. I had to go back to a previous lab to get the content necessary for this one.

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #15.

-- Flatiron Curriculum Team
