### ISSUE TITLE
Missing files prevents working on this lesson

### ISSUE THREAD

**Issue by stimsong** [learn-co-curriculum/layouts-grids-code-along#11]
Hello,

This code-along is still missing the necessary files to work on. Since Learn.co is configured to basically only work on the current lesson we are on and we aren't manually using a Git repository that we are continuing to update, this is a big problem. And it seems to have been around for a long time. 

Everything has been great up until this point but this is troubling. It makes me wonder if there are other lessons that have the same problem later on? I'm in the Community-powered version of Full-Stack Web Development, which is supposed to be the same as the Online version. Does this problem exist with the Online Web Developer program as well?

I will continue with the Community-powered course for now but this kind of issue would stop me from considering changing to the Online-version at some point.

Thanks,
Greg

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #15.

-- Flatiron Curriculum Team
