### ISSUE TITLE
LearnIDE file empty

### ISSUE THREAD

**Issue by kirbycampbell** [learn-co-curriculum/layouts-grids-code-along#12]
I merged files like in the video, yet there is no way to have this project submit successfully with these files. So I'm submitting the blank file that came along with this. It would be much nicer if this lesson was updated to work with the LearnIDE3 and the website projects we were building previously. I'm essentially learning bootstrap much better via googling modern sources than this video/project.  

Thanks,
K

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #15. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
