### ISSUE TITLE
Lesson Broken, doesn't load.

### ISSUE THREAD

**Issue by malbazaz** [learn-co-curriculum/layouts-grids-code-along#14]
Please let me know when it is fixed so I can revisit the lesson. Thanks.
Error:
b:19:in `classify'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/opener.rb
:36:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/opener.rb
:11:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/bin/learn-open:7:in `<to
p (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-open:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-open:23:in `<main>'
[12:38:38] ~

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
