### ISSUE TITLE
File Structure Confusion

### ISSUE THREAD

**Issue by nicolefederici** [learn-co-curriculum/layouts-grids-code-along#2]
Hi. I'm spending most of my time on Learn trying to figure out how to submit lessons rather than learning how to code. The discrepancy between the process of coding up a lesson and submitting it and what is actually described in the videos is vast. Vast. In addition to this, the online teachers don't seem to grasp this issue fully so they can explain how to navigate through to passing lessons. Please make the videos actually jive with the actual process of using the command line to set up directories and copy files to prepare for the codealong. The process has not been a process with predictable or expected protocols. (which is, I think, the best way to teach a beginner how to learn to choose the correct protocol to fit a given problem) In the immediate term, please! add notes below the videos explaining how the current process differs from what is described in the video so that students can proceed correctly and not waste their precious practice time. By the time I get coding/"learning", I'm already tired, frustrated and bored. I'd like to give a shout out to Kate, your teacher who helped me figure out what a merge conflict was for several hours one day- she knows how to teach- pay her more! (I'd rather not spend all of my time doing merge conflicts) Thanks so much! Nicole

**Comment by AnnJohn** [comment]
thank you @nicolefederici for this feedback. We're aware that our HTML/CSS lessons because they are video based have this problem. We're in the process of updating all of our HTML/CSS content and adding text to them. 

cc' @jongrover

**Comment by lukegrecki** [comment]
+1

This is a pretty annoying gap and it makes for a good amount of friction finishing these labs.

**Comment by jenmyers** [comment]
A new version of this material will also be available soon. Progress can be tracked at #15.

-- Flatiron Curriculum Team
