### ISSUE TITLE
Bootstrap codealong improvements

### ISSUE THREAD

**Issue by bhabig** [learn-co-curriculum/layouts-grids-code-along#3]
I would like to see files on github with the full contents of the files and folders being used in the actual codealong. I.e. if he is making changes to an index.html file in our bootstrapped folder, i want to see the final contents of that file available for me to comb through on github.

thanks!

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #15.

-- Flatiron Curriculum Team
