### ISSUE TITLE
Learn Submit not registering on learn.co website

### ISSUE THREAD

**Issue by byojelly** [learn-co-curriculum/layouts-grids-code-along#6]
ivalentine 8 MINUTES AGO
Hi Alex! How's it going?
byojelly 8 MINUTES AGO
good

byojelly 7 MINUTES AGO
i did my coding for the code along in a sepeerate folder from the lab

byojelly 7 MINUTES AGO
after the the code along i was able to copy the code into the labs folder

byojelly 7 MINUTES AGO
i then git add .

byojelly 7 MINUTES AGO
git commit

byojelly 7 MINUTES AGO
and then pushed the changes to the git hub repository

byojelly 6 MINUTES AGO
the learn.co website for the lesson is not turning over to green though

byojelly 6 MINUTES AGO
after the learn submit query

byojelly 6 MINUTES AGO
ive tried refreshing and several learn submit attempts

howardbdev 4 MINUTES AGO
yeah it's happening a lot right now, you can just move on to the next lesson

howardbdev 2 MINUTES AGO
just click 'next lesson' -- you won't be able to run the learn open command, but you can still open with the blue 'open' button if it's a lab or by forking/cloning manually

pbhagyashri A MINUTE AGO
I am having the same issue.

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

In fact, there's a great article about this very issue over in the [Learn Help Center](http://help.learn.co/). Check it out! 🎉

If you still require assistance after reading the Help Center article, pop into [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can provide additional help. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
