### ISSUE TITLE
The end of the CSS Section is PROBLEMATIC

### ISSUE THREAD

**Issue by kostanzhoglo** [learn-co-curriculum/layouts-grids-code-along#8]
Hello,

There is a serious error at the end of the CSS/Bootstrap section that needs to be solved.  The labs with Jonathan building his Exceptional Realty Website are informative, but the breakdown occurs because the lessons are unclear as to which version of his code you're working with.

I had to find files from previous labs in order to finish this one.  It's not appropriate for Flatiron to do this.  And it wouldn't take too much effort to fix this issue (I don't think).  If I'm wrong, please let me know.

Sadly, from reading the previous "issues" here, it doesn't seem like fixing this lesson is a priority for Flatiron.  Previous people have written similar critiques, and some go back over 2 years!  I hope they do solve it sooner than later.

Thank you,
J

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #15.

-- Flatiron Curriculum Team
