### ISSUE TITLE
Bootstrap Codealongs

### ISSUE THREAD

**Issue by JeamayPalo** [learn-co-curriculum/layouts-grids-code-along#9]
I am having a problem with the following lessons under the Boostrap framework: The Bootstrap Codealong, the Bootstrap Grid System, Layout Grid Codealong and Bootstrap Navbar codealongs. 

In the last 2 lesson of this chapter (Layout Grid Codealong and Bootstrap Navbar codealongs), it seems to need work that is done from the previous 2 lessons. However, the previous 2 lessons were only on Sandbox, and were therefore not saving anything. When I talked to technical coaches, they said I needed to push it to github anyway. But Sandbox was not able to open the zipfiles from bootstrap, so what  I did was I opened IDE  in my Layout Grid lesson, and did the  Bootstrap Codealong lesson in that file instead. However, all the exceptional realty files do not exist in that IDE either.

The coaches have been helpful, but they too aren't sure whether these 4 labs should be built on one another or if two of them are just codealongs and the other 2 are what you need to push to github. Either way, there are no  exceptional realty files on either of the lessons, so I don't know where to write my code. Is there something I'm missing? I'm not sure how to proceed with these lessons.

**Comment by jenmyers** [comment]
Hello! We have added some instructions to clarify how to manually track progress. A new version of this material will also be available soon. Progress can be tracked at #15.

-- Flatiron Curriculum Team
